Vagrant.configure("2") do |config|
  config.vm.define "node" do |node|
    node.vm.box = "bento/ubuntu-22.04"
    node.vm.hostname = "node"
    node.vm.network "public_network", bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
    node.vm.provision "shell", inline: <<-SHELL
      sudo ufw allow 22
      sudo ufw enable
      git clone https://github.com/faizan35/kubernetes_cluster_with_kubeadm.git
      cd kubernetes_cluster_with_kubeadm/vagrant/
      cp -r scripts ../../scripts
      chmod +x ../../scripts/*
      sudo rm -rf ~/kubernetes_cluster_with_kubeadm/
    SHELL

    # node.vm.provision "file", source: "../scripts/", destination: "/home/vagrant/", run: "always"
  end
end

