Vagrant.configure("2") do |config|
  config.vm.define "py" do |py|
    py.vm.box = "bento/ubuntu-22.04"
    py.vm.hostname = "py"
    # py.vm.network "public_network", bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter", mac: "08002710F69E"
    # If the above line causes issues, you can uncomment the next line to choose manually
    py.vm.network "public_network"
    py.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end
end
