Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "bento/ubuntu-22.04"
    master.vm.hostname = "master"
    master.vm.network "public_network", bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    master.vm.provision "shell", inline: <<-SHELL
      sudo ufw allow 22
      sudo ufw enable
      # Add your commands here
    SHELL

    master.vm.provision "file", source: "../scripts/", destination: "/home/vagrant/scripts/", run: "always"
  end
end
