Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "bento/ubuntu-22.04"
    master.vm.hostname = "master"
    master.vm.network "public_network", bridge: "Your-Bridge-Adapter-name"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    master.vm.provision "shell", inline: <<-SHELL
      sudo ufw allow 22
      sudo ufw enable
      git clone https://github.com/faizan35/kubernetes_cluster_with_kubeadm.git
      cd kubernetes_cluster_with_kubeadm/vagrant/
      cp -r scripts ../../scripts
      chmod +x ../../scripts/*
      cd ~
      sudo rm -rf ~/kubernetes_cluster_with_kubeadm/

    SHELL

    # master.vm.provision "file", source: "../scripts/", destination: "/home/vagrant/", run: "always"
  end
end
